import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'error': '#ffb4ab',
        'on-background': '#ebe2d0',
        'on-primary-container': '#6c5700',
        'on-tertiary-fixed': '#001f25',
        'secondary': '#4de082',
        'surface-container': '#231f14',
        'tertiary': '#c7f5ff',
        'inverse-primary': '#735c00',
        'on-secondary': '#003919',
        'tertiary-container': '#33e4ff',
        'background': '#171309',
        'on-primary-fixed-variant': '#574500',
        'surface-variant': '#393428',
        'on-tertiary-container': '#006270',
        'surface-container-highest': '#393428',
        'error-container': '#93000a',
        'on-surface': '#ebe2d0',
        'outline': '#9a9078',
        'on-secondary-fixed': '#00210c',
        'inverse-on-surface': '#353024',
        'on-surface-variant': '#d1c6ab',
        'surface-container-lowest': '#110e05',
        'primary-container': '#facc15',
        'on-primary': '#3c2f00',
        'outline-variant': '#4d4632',
        'on-secondary-fixed-variant': '#005227',
        'on-tertiary-fixed-variant': '#004e59',
        'surface': '#171309',
        'tertiary-fixed-dim': '#15daf4',
        'surface-tint': '#eec200',
        'secondary-fixed': '#6dfe9c',
        'surface-container-low': '#1f1b11',
        'surface-container-high': '#2e2a1e',
        'secondary-container': '#00b55d',
        'primary-fixed': '#ffe083',
        'secondary-fixed-dim': '#4de082',
        'primary-fixed-dim': '#eec200',
        'tertiary-fixed': '#a0efff',
        'surface-bright': '#3e392d',
        'primary': '#ffecb9',
        'on-tertiary': '#00363e',
        'on-error': '#690005',
        'inverse-surface': '#ebe2d0',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#231b00',
        'on-secondary-container': '#003e1c',
        'surface-dim': '#171309',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        'unit': '4px',
        'margin-mobile': '16px',
        'editor-padding': '40px',
        'gutter': '16px',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'editor-main': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'editor-chord': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'editor-main': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'editor-chord': ['16px', { lineHeight: '1.4', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms],
}
